---
id: Text_Diff
name: Text_Diff
full: Text diff generation and rendering library
description: >-
  A library that provides a text-based diff engine and renderers for multiple
  diff output formats.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Text_Diff
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  - name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0
  api: 3.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^8.1
    composer:
      horde/exception: ^3
      horde/util: ^3
  optional:
    composer:
      horde/cli: ^3
    ext:
      xdiff: '*'
  dev:
    composer:
      horde/cli: ^3
      horde/test: ^3
vendor: horde
keywords: null
ci-platform:
  '8.1':
    - php: ^7.4 || ^8
    - ext-dom
  '8.2':
    - php: ^7.4 || ^8
    - ext-dom
  '8.3':
    - php: ^7.4 || ^8
    - ext-dom
  '8.4':
    - php: ^7.4 || ^8
    - ext-dom
  '8.5':
    - php: ^7.4 || ^8
    - ext-dom
  '8.6':
    - php: ^7.4 || ^8
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
