---
id: Text_Diff
name: Text_Diff
full: Text diff generation and rendering library
description: >-
  A library that provides a text-based diff engine and renderers for multiple
  diff output formats.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Text_Diff
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha4
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
  optional:
    composer:
      horde/cli: ^3
      horde/test: ^3
    ext:
      xdiff: '*'
